spring:
  application:
    name: school-student
  profiles:
    default: mysql-container
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

springdoc:
  api-docs:
    path: /electronic/school/api-docs

server:
  port: 8093
api:
  server:
    url: http://localhost:8093
# Enter to OpenDocs = http://localhost:8093/swagger-ui/index.html
lessonsAndCertificates:
  getLessonName:
    url: http://school-lessons-and-certificates:8092/lessonsAndCertificates/getLessonName
  deleteStudentCertificates:
    url: http://school-lessons-and-certificates:8092/lessonsAndCertificates/deleteStudentCertificates
  createCertificates:
    url: http://school-lessons-and-certificates:8092/lessonsAndCertificates/createCertificates